---

- name: Set timezone to Asia/Seoul
  timezone:
    name: Asia/Seoul
  become: yes

- name: Update Yum Packages
  yum:
    name: '*'
    state: latest
  become: yes

- name: Install packages
  yum:
    name: java-1.8.0-openjdk-devel.x86_64
    state: present
  become: yes
