node {
    stage('Clone repository') {
        git 'https://github.com/HaJaeKwon/book-Getting-Started-with-Docker-Kubernetes.git'
    }

    dir('2장_도커_엔진_task') {
        stage('Test') {
            sh './gradlew test'
        }
        stage('Build') {
            sh './gradlew clean assemble'
            sh 'cp ./build/libs/demo.jar ./'
        }
    }
    stage('Build Image') {
        app = docker.build("hazxz/2-weekend", "./2장_도커_엔진_task")
    }
    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub') {
            app.push("${env.BUILD_ID}")
            app.push("latest")
        }
    }
}
