# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.network "private_network", ip: "192.168.1.1"
    config.vm.network "forwarded_port", guest: 22, host: 1234, id: "ssh"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 4
    end
  config.vm.box = "centos/7"
	config.vm.provision "shell", inline: <<-SHELL
		yum install net-tools -y
		yum install bridge-utils -y
	SHELL
	config.vm.provision :docker,
		images: ["ubuntu:14.04"]
end
