node {
    stage('Test') {
        ./gradlew test
    }

    stage('Build Image') {
        docker build -t 2-weekend-demo
    }

    stage('Save Image') {
        sh "echo 'Save Image'"
    }

    stage('Load Image') {
        sh "echo 'Load Image'"
    }

    stage('Start Image') {
        docker run -p 9090:9090 2-weekend-demo
    }
}
