pipeline {
    agent none
    options { skipDefaultCheckout(true) }
    stages {
        stage('Git Checkout') {
            agent any
            steps {
                git 'https://github.com/HaJaeKwon/book-Getting-Started-with-Docker-Kubernetes.git'
            }
        }

        dir('/2장\ 도커\ 엔진\ task/') {
            stage('Test And Build') {
                agent any
                steps {
                    sh './gradlew test'
                }
                steps {
                    sh './gradlew clean assemble'
                }
            }

            stage('Build Image') {
                agent any
                steps {
                    sh 'docker build -t 2-chapter-demo:latest .'
                }
            }

            stage('Save Image') {
                agent any
                sh "echo 'Save Image'"
            }

            stage('Load Image') {
                agent any
                sh "echo 'Load Image'"
            }

            stage('Start Image') {
                agent any
                sh 'docker run -p 9090:9090 2-chapter-demo'
            }
        }
    }
}
