---

- name: Check that jenkins.war file exists
  stat:
    path: /home/vagrant/jenkins.war
  register: jenkins_file_result

- name: Download jenkins.war file
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /home/vagrant/jenkins.war
    timeout: 1000
  when: not jenkins_file_result.stat.exists

- name: Check jenkins is running
  shell: ps -ef |grep 'java -jar jenkins.war' |grep -v grep
  register: jenkins_running_result

- block:

  - name: Create nohup script
    template:
      src: start_jenkins.sh.j2
      dest: /home/vagrant/start_jenkins.sh
      mode: 0755

  - name: Start jenkins.war
    command: sh start_jenkins.sh
    args:
      chdir: /home/vagrant

  - name: Register var of jenkins initialAdminPassword
    shell:
      cmd: cat /home/vagrant/.jenkins/secrets/initialAdminPassword
    register: initialAdminPassword_result
    ignore_errors: yes
    become: yes

  - name: Print initialAdminPassword
    debug:
      msg: init password is {{ initialAdminPassword_result }}
    when: initialAdminPassword_result is defined

  when: jenkins_running_result.stdout_lines|length == 0
